# Generated by Django 5.2.5 on 2026-01-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_questionpaper_is_active_alter_paperquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
    ]
