# Generated by Django 5.2.5 on 2026-01-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_is_common'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='question_paper',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='Primary', help_text='Select whether this is a Primary or Secondary paper', max_length=20),
        ),
    ]
