# Generated by Django 5.2.5 on 2026-01-24 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_questionpaper_question_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='is_common',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='part_distribution',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='qp_assign',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='trade',
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='exam_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=10800)),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='question_paper',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PaperQuestion',
        ),
    ]
