# Generated by Django 5.2.5 on 2026-01-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_questionpaper_questions_and_more'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePaperActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('exam_duration', models.DurationField(blank=True, help_text='Optional override for this trade+paper_type. If empty, uses QuestionPaper.exam_duration.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade Paper Activation',
                'verbose_name_plural': 'Trade Paper Activations',
                'ordering': ['trade__code', 'paper_type'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='paper_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], db_index=True, default='PRIMARY', help_text='PRIMARY for trade-specific questions. SECONDARY for common questions (trade=ALL -> trade NULL).', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionupload',
            name='trade',
            field=models.ForeignKey(blank=True, help_text="If set, all imported questions will be tagged with this trade. For unified DAT, keep this blank and use Excel 'trade' column.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trade'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['paper_type', 'trade', 'is_active'], name='questions_q_paper_t_76f7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['part', 'paper_type', 'trade'], name='questions_q_part_bfa01b_idx'),
        ),
        migrations.AddField(
            model_name='tradepaperactivation',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.trade'),
        ),
        migrations.AlterUniqueTogether(
            name='tradepaperactivation',
            unique_together={('trade', 'paper_type')},
        ),
    ]
