# Generated by Django 5.2.5 on 2026-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_tradepaperactivation_question_paper_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradepaperactivation',
            options={'ordering': ['trade__name', 'paper_type'], 'verbose_name': 'Trade Paper Activation', 'verbose_name_plural': 'Trade Paper Activations'},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_paper_t_76f7c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_part_bfa01b_idx',
        ),
        migrations.RemoveField(
            model_name='questionupload',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='tradepaperactivation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='question',
            name='paper_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='PRIMARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='question_paper',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tradepaperactivation',
            name='exam_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
