# Generated by Django 5.2.5 on 2026-01-27 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_tradepaperactivation_options_and_more'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaperTypeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_activated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Paper Type Control',
                'verbose_name_plural': 'Global Paper Type Controls',
            },
        ),
        migrations.CreateModel(
            name='QuestionSetActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20)),
                ('question_set', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Set Activation',
                'verbose_name_plural': 'Question Set Activations',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_set',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='A', help_text='Question set identifier (A-Z)', max_length=1),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['trade', 'paper_type', 'question_set', 'is_active'], name='questions_q_trade_i_9b20ed_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_set', 'part'], name='questions_q_questio_3f69ff_idx'),
        ),
        migrations.AddField(
            model_name='globalpapertypecontrol',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsetactivation',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsetactivation',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.trade'),
        ),
        migrations.AddIndex(
            model_name='questionsetactivation',
            index=models.Index(fields=['trade', 'paper_type', 'is_active'], name='questions_q_trade_i_19e123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionsetactivation',
            unique_together={('trade', 'paper_type', 'question_set')},
        ),
    ]
