# Generated by Django 5.2.5 on 2026-01-27 18:49

from django.db import migrations


def migrate_existing_questions(apps, schema_editor):
    """Migrate existing questions to use question_set field"""
    Question = apps.get_model('questions', 'Question')
    
    # Assign all existing questions to set 'A'
    Question.objects.filter(question_set__isnull=True).update(question_set='A')
    
    # Convert existing JSON options to separate fields where possible
    for question in Question.objects.filter(
        option_a__isnull=True,
        options__isnull=False
    ):
        if isinstance(question.options, list) and len(question.options) >= 4:
            question.option_a = question.options[0]
            question.option_b = question.options[1] 
            question.option_c = question.options[2]
            question.option_d = question.options[3]
            question.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_add_question_set_management'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_questions, reverse_migration),
    ]
