# Generated by Django 5.2.5 on 2026-01-28 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_add_activate_sets_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalSetActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20, unique=True)),
                ('universal_set_label', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], help_text='Universal question set for all trades (leave blank for individual trade selection)', max_length=1, null=True)),
                ('universal_duration_minutes', models.IntegerField(blank=True, help_text='Universal exam duration in minutes for all trades (leave blank for individual trade durations)', null=True)),
                ('is_universal_set_active', models.BooleanField(default=False, help_text='Enable universal set activation (same set for all trades)')),
                ('is_universal_duration_active', models.BooleanField(default=False, help_text='Enable universal duration (same duration for all trades)')),
                ('activated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Universal Set Activation',
                'verbose_name_plural': 'Universal Set Activations',
            },
        ),
    ]
