# Generated by Django 5.2.5 on 2026-02-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_universalsetactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='exam_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='PRIMARY', max_length=20),
            preserve_default=False,
        ),
    ]
