#!/usr/bin/env python
"""
Test question generation to debug the count issue
"""
import os
import django

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from django.contrib.auth import get_user_model
from registration.models import CandidateProfile
from questions.models import QuestionPaper, ExamSession, TradePaperActivation, QuestionSetActivation
from reference.models import Trade

User = get_user_model()

def test_question_generation():
    """Test actual question generation for the candidate"""
    
    try:
        candidate = CandidateProfile.objects.get(army_no='12345')
        trade = candidate.trade
        
        print(f"Testing question generation for {candidate.name} (Trade: {trade})")
        
        # Get active activation
        activation = TradePaperActivation.objects.filter(
            trade=trade,
            is_active=True
        ).first()
        
        if not activation:
            print("No active activation found!")
            return
            
        print(f"Active paper type: {activation.paper_type}")
        
        # Get paper
        paper = QuestionPaper.objects.filter(
            question_paper=activation.paper_type,
            is_active=True
        ).first()
        
        if not paper:
            print("No active paper found!")
            return
            
        print(f"Paper: {paper}")
        
        # Clear any existing sessions for this test
        ExamSession.objects.filter(user=candidate.user, paper=paper).delete()
        
        # Generate new session
        try:
            session = paper.generate_for_candidate(
                user=candidate.user,
                trade=trade
            )
            
            print(f"Session created with {session.total_questions} questions")
            
            # Get questions by part
            questions = session.questions.all()
            part_counts = {}
            
            for q in questions:
                part = q.question.part
                if part not in part_counts:
                    part_counts[part] = 0
                part_counts[part] += 1
            
            print("Questions generated by part:")
            total = 0
            for part in sorted(part_counts.keys()):
                count = part_counts[part]
                print(f"  Part {part}: {count} questions")
                total += count
            
            print(f"Total questions generated: {total}")
            
            # Show first few questions for verification
            print("\nFirst 5 questions:")
            for i, eq in enumerate(questions[:5]):
                print(f"  {i+1}. [{eq.question.part}] {eq.question.text[:60]}...")
            
        except Exception as e:
            print(f"Error generating session: {e}")
            import traceback
            traceback.print_exc()
            
    except CandidateProfile.DoesNotExist:
        print("Candidate not found!")

if __name__ == '__main__':
    test_question_generation()