# Generated by Django 5.2.5 on 2026-01-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OIC_ADMIN', 'OIC Admin'), ('CANDIDATE', 'Candidate'), ('PO_ADMIN', 'PO Admin')], db_index=True, default='CANDIDATE', max_length=32),
        ),
    ]
