# Generated by Django 5.2.5 on 2026-01-27 20:04

from django.db import migrations


def migrate_center_admin_to_oic(apps, schema_editor):
    """Migrate existing CENTER_ADMIN users to OIC_ADMIN"""
    User = apps.get_model('accounts', 'User')
    
    # Update all CENTER_ADMIN users to OIC_ADMIN
    updated_count = User.objects.filter(role='CENTER_ADMIN').update(role='OIC_ADMIN')
    
    if updated_count > 0:
        print(f"Migrated {updated_count} CENTER_ADMIN users to OIC_ADMIN")


def reverse_migrate_oic_to_center_admin(apps, schema_editor):
    """Reverse migration: OIC_ADMIN back to CENTER_ADMIN"""
    User = apps.get_model('accounts', 'User')
    
    # Update all OIC_ADMIN users back to CENTER_ADMIN
    updated_count = User.objects.filter(role='OIC_ADMIN').update(role='CENTER_ADMIN')
    
    if updated_count > 0:
        print(f"Reverted {updated_count} OIC_ADMIN users back to CENTER_ADMIN")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_center_admin_to_oic'),
    ]

    operations = [
        migrations.RunPython(
            migrate_center_admin_to_oic,
            reverse_migrate_oic_to_center_admin
        ),
    ]
