# Generated by Django 5.2.5 on 2026-01-24 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')], verbose_name='Mobile No (Linked to Aadhaar Card)'),
        ),
    ]
