# Generated by Django 5.2.5 on 2026-01-27 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_candidateprofile_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 12-digit APAAR ID.', regex='^\\d{12}$')], verbose_name='APAAR ID (12 digits)'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')], verbose_name='Mobile No (Linked to Aadhaar Card)'),
        ),
    ]
