# Generated by Django 5.2.5 on 2026-01-27 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_add_apaar_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='has_exam_slot',
            field=models.BooleanField(default=False, verbose_name='Has Exam Slot'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='slot_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Slot Assigned At'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='slot_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_slots', to=settings.AUTH_USER_MODEL, verbose_name='Slot Assigned By'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='slot_consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
    ]
