# Generated by Django 5.2.5 on 2026-01-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_add_exam_slot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='slot_attempting_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exam Attempt Started At'),
        ),
    ]
