# Generated by Django 5.2.5 on 2026-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_add_slot_attempting_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_primary_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_secondary_completed',
            field=models.BooleanField(default=False),
        ),
    ]
