# Generated by Django 5.2.5 on 2026-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_candidateprofile_is_primary_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='primary_bypass_allowed',
            field=models.BooleanField(default=False, help_text='Allow candidate to give SECONDARY without completing PRIMARY (legacy / failed earlier)'),
        ),
    ]
