# Generated by Django 5.2.5 on 2026-01-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_candidateprofile_primary_bypass_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='slot_consumed_at',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='primary_slot_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_slot_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
