# Generated by Django 5.2.5 on 2026-01-31 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_candidateprofile_slot_consumed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='apaar_id',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='APAAR ID must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='APAAR ID (12 digits)'),
        ),
    ]
