# Generated by Django 5.2.5 on 2026-01-31 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_candidateprofile_apaar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='aadhar_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
    ]
