"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from .security_config import SecurityConfig, EnvironmentLoader

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if it exists
EnvironmentLoader.load_env_file(BASE_DIR / '.env')

# =============================================================================
# SECURITY CONFIGURATION - Using Environment Variables
# =============================================================================

# SECURITY: Load secret key from environment variables
SECRET_KEY = SecurityConfig.load_secret_key()

# SECURITY: Debug mode controlled by environment
DEBUG = SecurityConfig.is_debug_enabled()

# SECURITY: Allowed hosts from environment variables
ALLOWED_HOSTS = SecurityConfig.get_allowed_hosts()


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "import_export",
    "django_filters",
    "config",  # Add config app for management commands
    "accounts",
    "reference.apps.ReferenceConfig",
    "centers",
    "registration",
    "questions.apps.QuestionsConfig",
    "exams",
    "results",
    "deletedata.apps.DeletedataConfig",
    "syncops",
]

# =============================================================================
# SECURITY MIDDLEWARE - Enhanced Security Headers
# =============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =============================================================================
# HTTPS AND SECURITY HEADERS
# =============================================================================

# HTTPS Configuration
SECURE_SSL_REDIRECT = EnvironmentLoader.get_bool_env('SECURE_SSL_REDIRECT', False)
SECURE_HSTS_SECONDS = EnvironmentLoader.get_int_env('SECURE_HSTS_SECONDS', 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = EnvironmentLoader.get_bool_env('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = EnvironmentLoader.get_bool_env('SECURE_HSTS_PRELOAD', False)

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = EnvironmentLoader.get_bool_env('SECURE_CONTENT_TYPE_NOSNIFF', True)
SECURE_BROWSER_XSS_FILTER = EnvironmentLoader.get_bool_env('SECURE_BROWSER_XSS_FILTER', True)
X_FRAME_OPTIONS = EnvironmentLoader.get_env_var('X_FRAME_OPTIONS', 'DENY')

# Session and CSRF Security
SESSION_COOKIE_SECURE = EnvironmentLoader.get_bool_env('SESSION_COOKIE_SECURE', False)
CSRF_COOKIE_SECURE = EnvironmentLoader.get_bool_env('CSRF_COOKIE_SECURE', False)
SESSION_COOKIE_HTTPONLY = EnvironmentLoader.get_bool_env('SESSION_COOKIE_HTTPONLY', True)
CSRF_COOKIE_HTTPONLY = EnvironmentLoader.get_bool_env('CSRF_COOKIE_HTTPONLY', True)

# Session Configuration
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# =============================================================================
# DATABASE CONFIGURATION - Using Environment Variables
# =============================================================================

# SECURITY: Database configuration from environment variables
try:
    DATABASES = {
        'default': SecurityConfig.get_database_config()
    }
except Exception as e:
    # Fallback for development if environment variables are not set
    if DEBUG:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'exam_portal',
                'USER': 'root',
                'PASSWORD': 'root',
                'HOST': 'localhost',
                'PORT': '3306',
            }
        }
    else:
        raise e



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

AUTH_USER_MODEL = "accounts.User"

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "candidate_dashboard"
LOGOUT_REDIRECT_URL = "login"
LOGIN_URL = "login"



STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "config" / "static",   # since your static is inside config/
]


JAZZMIN_SETTINGS = {
    "site_title": "2 STC Online Exam Portal",
    "site_header": "2 STC",
    "site_brand": "2 STC Portal",
    "welcome_sign": "JAI HIND! Welcome to 2STC Online Exam Portal",
    "copyright": "Developed by SLOG Solutions Pvt Ltd and 2STC",
    
    # Logo settings
    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "login_logo_dark": "img/logo.png",
    
    # Icons configuration
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "exams.Exam": "fas fa-file-alt",
        "exams.Question": "fas fa-question-circle",
        "exams.Result": "fas fa-chart-line",
        "students.Student": "fas fa-user-graduate",
        "deletedata.ExamDataCleanup": "fas fa-trash-alt",
    },
    
    # Top menu links
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Data Management", "url": "admin:deletedata_examdatacleanup_changelist", "permissions": ["auth.view_user"], "icon": "fas fa-database"},
        {"name": "Support", "url": "https://www.slogsolutions.com", "new_window": True},
    ],
    
    # UI tweaks
    "show_ui_builder": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "centers",
        "exams",
        "questions",
        "registration",
        "users"   # <= Users section will be here, below Registration
    ],

    
    # # Order apps
    # # "order_with_respect_to": ["auth", "exams", "students"],
    
    # # Custom links
    # "custom_links": {
    #     "exams": [{
    #         "name": "Generate Reports", 
    #         "url": "generate_reports", 
    #         "icon": "fas fa-chart-pie",
    #         "permissions": ["exams.view_result"]
    #     }]
    # },
    

    
    # Show sidebar
    "show_sidebar": True,
    
    # Language
    "language_chooser": False,
    "custom_css": "css/admin-overrides.css",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cyborg",
    "dark_mode_theme": None,
    "navbar": "navbar-dark navbar-primary",
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "accent": "accent-primary",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
# =============================================================================
# FILE UPLOAD CONFIGURATION - Using Environment Variables
# =============================================================================

FILE_UPLOAD_MAX_MEMORY_SIZE = EnvironmentLoader.get_int_env('FILE_UPLOAD_MAX_MEMORY_SIZE', 104857600)  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = EnvironmentLoader.get_int_env('DATA_UPLOAD_MAX_MEMORY_SIZE', 104857600)  # 100MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = EnvironmentLoader.get_int_env('DATA_UPLOAD_MAX_NUMBER_FIELDS', 100000)

# =============================================================================
# EXAM PORTAL SPECIFIC CONFIGURATION - Using Environment Variables
# =============================================================================

EXAM_UNIFIED_DAT_ENABLED = EnvironmentLoader.get_bool_env('EXAM_UNIFIED_DAT_ENABLED', True)
CONVERTER_PASSPHRASE = EnvironmentLoader.get_env_var('CONVERTER_PASSPHRASE', 'bharat')

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

LOG_LEVEL = EnvironmentLoader.get_env_var('LOG_LEVEL', 'INFO')
LOG_FILE_PATH = EnvironmentLoader.get_env_var('LOG_FILE_PATH', 'logs/exam_portal.log')

# Ensure log directory exists
import os
log_dir = os.path.dirname(LOG_FILE_PATH)
if log_dir and not os.path.exists(log_dir):
    os.makedirs(log_dir, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',  # Suppress DEBUG logs from Django
            'propagate': False,
        },
        'django.utils.autoreload': {
            'handlers': ['console'],
            'level': 'WARNING',  # Suppress file monitoring DEBUG logs
            'propagate': False,
        },
        'django.template': {
            'handlers': ['console'],
            'level': 'INFO',  # Suppress template DEBUG logs
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',  # Suppress SQL query DEBUG logs
            'propagate': False,
        },
        'questions': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'registration': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Add file handler only if we can write to the log file
try:
    # Test if we can write to the log file
    with open(LOG_FILE_PATH, 'a') as f:
        pass
    
    # Add file handler if successful
    LOGGING['handlers']['file'] = {
        'level': LOG_LEVEL,
        'class': 'logging.FileHandler',
        'filename': LOG_FILE_PATH,
        'formatter': 'verbose',
    }
    
    # Update handlers to include file logging
    for logger_config in LOGGING['loggers'].values():
        logger_config['handlers'].append('file')
    LOGGING['root']['handlers'].append('file')
    
except (OSError, PermissionError):
    # If we can't write to the log file, just use console logging
    pass
    

# =============================================================================
# SECURITY VALIDATION
# =============================================================================

# Validate security settings on startup
if not DEBUG:
    try:
        SecurityConfig.validate_security_settings()
        
        # Additional production validation
        from .security_config import SecureSettingsValidator
        validation_errors = SecureSettingsValidator.validate_production_settings(locals())
        
        if validation_errors:
            import sys
            print("SECURITY VALIDATION ERRORS:")
            for error in validation_errors:
                print(f"  - {error}")
            print("\nPlease fix these security issues before running in production.")
            sys.exit(1)
            
    except Exception as e:
        import sys
        print(f"SECURITY CONFIGURATION ERROR: {e}")
        print("Please check your environment variables and configuration.")
        sys.exit(1)